### ISSUE TITLE
Failed to download: not well-formed (invalid token): line 27, column 80

### ISSUE THREAD

**Issue by J535D165** [J535D165/datahugger#36]
```bash
% datahugger https://hdl.handle.net/10622/NHJZUD tmp --log-level DEBUG
Collecting...
DEBUG:root:Resolve service: search netloc 'hdl.handle.net'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): doi.org:443
DEBUG:urllib3.connectionpool:https://doi.org:443 "GET /None HTTP/1.1" 404 None
Traceback (most recent call last):
  File "/Users/.../versions/sra-dev/bin/datahugger", line 8, in <module>
    sys.exit(main())
  File "/Users/.../datahugger/datahugger/__main__.py", line 104, in main
    raise err
  File "/Users/.../datahugger/datahugger/__main__.py", line 83, in main
    get(
  File "/Users/.../datahugger/datahugger/api.py", line 267, in get
    return _base_request(
  File "/Users/.../datahugger/datahugger/api.py", line 206, in _base_request
    service_class = _resolve_service(url, doi)
  File "/Users/.../datahugger/datahugger/api.py", line 318, in _resolve_service
    service_class = _resolve_service_with_re3data(doi)
  File "/Users/.../datahugger/datahugger/api.py", line 343, in _resolve_service_with_re3data
    publisher = get_datapublisher_from_doi(doi)
  File "/Users/.../datahugger/datahugger/utils.py", line 100, in get_datapublisher_from_doi
    tree = ET.fromstring(r.content)
  File "/Users/.../versions/3.9.7/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 27, column 80
```

**Comment by J535D165** [comment]
```datahugger 10.1000/182 tmp100 --log-level DEBUG```

**Comment by J535D165** [comment]
Both examples work correctly in v0.8.
